ManajemenBarang/Areas/Supplier/Controllers/SuppliersiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ManajemenBarang.Models;
using ManajemenBarang.Areas.Supplier.Models;

namespace ManajemenBarang.Areas.Supplier.Controllers
{
    public class SuppliersiteController : Controller
    {
        // GET: Supplier/Suppliersite
        SupBar sb = new SupBar();
        InBarang ib = new InBarang();
        BarangWhere bw = new BarangWhere();
        public ActionResult Index(string id_supplier)
        {
            if (Session["SupID"] != null)
            {
                //string str = Session["SupID"].ToString();
                ViewModel vm = new ViewModel();
                id_supplier = Session["SupID"].ToString();
                //id_user = 1;
                vm.allBar = ib.GetBarangWhere3_Results(id_supplier);
                vm.allSup = ib.GetNama(id_supplier);
                //List<GetBarangWhere3_Result> bwh = bw.GetBarangWhere3_Results(id_supplier);
                return View(vm);

                //List<GetSupplay_Result> tess = sb.GetSupplay_Results();
                //tess.Where(a => a.id_supplier.Equals(Session["SupID"]));
                //return View(tess);
            }
            return View("ErrorSession");
        }
        
        public ActionResult Insert()
        {
            if (Session["SupID"] != null)
            {
                ViewModel vm = new ViewModel();
                vm.allKategori = ib.GetKategori_Results();
                return View("Create", vm);
            }
            return View("ErrorSession");
        }
        public ActionResult InsertExist(string id_supplier)
        {
            if (Session["SupID"] != null)
            {
                ViewModel vm = new ViewModel();
                //vm.allKategori = ib.GetKategori_Results();
                id_supplier = Session["SupID"].ToString();
                vm.allNya = ib.GetBarangnya_Results(id_supplier);
                //vm.allBarang = ib.GetBarang_Results();
                return View("CreateExist", vm);
            }
            return View("ErrorSession");
        }
        public ActionResult InsertData(GetBarangSup2_Result br)
        {
            dbStokEntities dbe = new dbStokEntities();
            dbe.CreateData2(br.id_kategori, br.id_supplier, br.kode_barang, br.nama_barang, br.id_barang, br.jumlah_barang, br.tanggal_masuk, br.jum_barang_masuk, br.created_masuk, br.deskripsi, br.updated_masuk);
            return View("InsertData");
        }
        public ActionResult InsertDataExist(GetBarangSup2_Result br)
        {
            dbStokEntities dbe = new dbStokEntities();
            dbe.CreateDataExist(br.id_barang, br.tanggal_masuk, br.jumlah_barang, br.deskripsi, br.created_masuk, br.id_supplier);
            return View("InsertDataExist");
        }
        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Login","Dashboard",new { area=""});
        }
        ProfilMod pm = new ProfilMod();
        public ActionResult Profil(string id_supplier)
        {
            if (Session["SupID"] != null)
            {
                id_supplier = Session["SupID"].ToString();
                List<GetProfil_Result> gpr = pm.GetProfil_Results(id_supplier);
                return View(gpr);
            }
            return View("ErrorSession");
        }
    }
}

ManajemenBarang/Areas/Supplier/Views/Suppliersite/Create.cshtml
@model ManajemenBarang.Areas.Supplier.Models.ViewModel
@{
    ViewBag.Title = "Create";
}

<h2>Tambah Data Barang</h2>
<div class="row">
    <div class="col-md-12">

        <form method="post" action="@Url.Action("InsertData", "Suppliersite")">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-md-6">

                <div class="form-group">
                    <label class="control-label">Kode Barang</label>
                    <input name="kode_barang" class="form-control" required autocomplete="off" />
                </div>
                <div class="form-group">
                    <label class="control-label">Nama Barang</label>
                    <input name="nama_barang" class="form-control" required autocomplete="off" />
                </div>

                <div class="form-group">

                    <label class="control-label">Kategori</label>
                    <select name="id_kategori" class="form-control" required>
                        @*Iterating Agama ViewModel *@
                        <option selected="selected" value="">--- Pilih Kategori ---</option>
                        @foreach (var itemK in Model.allKategori)
                        {
                            <option value="@itemK.id_kategori">@itemK.nama_kategori</option>
                        }
                    </select>

                </div>

                <div class="form-group">
                    <label class="control-label">Jumlah Barang</label>
                    <input name="jumlah_barang" class="form-control" onkeypress="return isNumberKey(event)" required autocomplete="off" />
                </div>

                <div class="form-group">
                    <label class="control-label">Deskripsi</label>
                    <!--<input name="deskripsi" class="form-control" required autocomplete="off" />-->
                    <textarea name="deskripsi" class="form-control" required maxlength="50"></textarea>
                    <input name="created_by" hidden="hidden" value="2" />
                    <input name="updated_by" hidden="hidden" value="2" />
                    <input name="id_supplier" hidden="hidden" value="@Session["SupID"]" />
                </div>

                <div class="form-group">
                    <input type="submit" value="Insert Data" class="btn btn-default" />
                </div>
            </div>
        </form>
    </div>
</div>
<div>
    @Html.ActionLink("Kembali", "Index")
</div>
<script>
    function isNumberKey(evt) {
        var charCode = (evt.which) ? evt.which : event.keyCode;
        if (charCode > 31
            && (charCode < 48 || charCode > 57))
            return false;

        return true;
    }
</script>

ManajemenBarang/Areas/Supplier/Views/Suppliersite/CreateExist.cshtml
@model ManajemenBarang.Areas.Supplier.Models.ViewModel
@{
    ViewBag.Title = "CreateExist";
}

<h2>Tambah Data Barang Existing</h2>
<div class="row">
    <div class="col-md-12">

        <form method="post" action="@Url.Action("InsertDataExist", "Suppliersite")">            
            <div class="col-md-6">

                <!--<div class="form-group">
                       <label class="control-label">Kode Barang</label>
                       @*foreach (var itemB in Model.allBarang)
                       {
                           <input name="kode_barang" class="form-control" required autocomplete="off" value="@Html.Display(itemB.kode_barang)" readonly />
                       }*@
                   </div>-->
                <div class="form-group">
                    <label class="control-label">Nama Barang</label>
                    <select name="id_barang" class="form-control" required>
                        @*Iterating Barang ViewModel *@
                        <option selected="selected" value="">--- Pilih Barang ---</option>
                        @foreach (var itemB in Model.allNya)
                        {
                            <option value="@itemB.id_barang">@itemB.nama_barang</option>
                        }
                    </select>
                </div>

                <!--<div class="form-group">

                      <label class="control-label">Kategori</label>
                      <select name="id_kategori" class="form-control" required>
                          @*Iterating Kategori ViewModel *@
                          <option selected="selected" value="">--- Pilih Kategori ---</option>
                          @*foreach (var itemK in Model.allKategori)
                          {
                              <option value="@itemK.id_kategori">@itemK.nama_kategori</option>
                          }*@
                      </select>

                  </div>-->

                <div class="form-group">
                    <label class="control-label">Jumlah Barang</label>
                    <input name="jumlah_barang" class="form-control" onkeypress="return isNumberKey(event)" required autocomplete="off" />
                </div>

                <div class="form-group">
                    <label class="control-label">Deskripsi</label>
                    <!--<input name="deskripsi" class="form-control" required autocomplete="off" />-->
                    <textarea name="deskripsi" class="form-control" required maxlength="50"></textarea>
                    <input name="created_by" hidden="hidden" value="2" />
                    <input name="updated_by" hidden="hidden" value="2" />
                    <input name="id_supplier" hidden="hidden" value="@Session["SupID"]" />
                </div>

                <div class="form-group">
                    <input type="submit" value="Insert Data" class="btn btn-default" />
                </div>
            </div>
        </form>
    </div>
</div>
<div>
    @Html.ActionLink("Kembali", "Index")
</div>
<script>
    function isNumberKey(evt) {
        var charCode = (evt.which) ? evt.which : event.keyCode;
        if (charCode > 31
            && (charCode < 48 || charCode > 57))
            return false;

        return true;
    }
</script>

ManajemenBarang/Areas/Supplier/Views/Suppliersite/ErrorSession.cshtml
@{
    ViewBag.Title = "ErrorSession";
}

<h2>Session Habis</h2>
<h4>Diharapkan Login Kembali</h4>
<p>
    @Html.RouteLink("Ke Halaman Login", "Default", new { action = "Login", controller = "Dashboard" })
</p>

ManajemenBarang/Areas/Supplier/Views/Suppliersite/Index.cshtml
@model ManajemenBarang.Areas.Supplier.Models.ViewModel
@{
    ViewBag.Title = "Index";
}

<h2>Supplier</h2>
<!-- <p style="margin-left:20px;float:right;margin-right:20px;">
    @*Html.RouteLink("Logout", "Default", new { action = "Login", controller = "Dashboard" })*@
</p> -->
<!--<p style="margin-left:20px;float:right;margin-right:20px;">
    @*Html.ActionLink("Logout", "Logout")*@
</p>-->
@if (Session["SupID"] != null)
{<text> Selamat Datang @Session["SupName"].ToString() </text>}
<!--<p>
    @Html.ActionLink("Tambah Data", "Insert")

</p>-->
<br />
<br />
<form style="float:right">
    <ul class="nav navbar-nav navbar-left">
        <li>
            <div class="btn-group">
                <button type="button" class="btn btn-link dropdown-toggle" data-toggle="dropdown">Tambah Data <div class="caret"></div></button>
                <!-- dropdown menu items-->
                <ul class="dropdown-menu" role="menu">
                    <li><a href="@Url.Action("Insert","Suppliersite", new { Area = "Supplier" })"><span class="glyphicon glyphicon-plus"></span> Tambah Data Baru</a></li>
                    <li><a href="@Url.Action("InsertExist","Suppliersite", new { Area = "Supplier" })"><span class="glyphicon glyphicon-pencil"></span> Tambah Data Existing</a></li>
                </ul>
            </div>
        </li>
    </ul>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                Nama Barang
            </th>
            <th>
                Kategori
            </th>
            <th>
                Total Barang
            </th>
            <th>
                Jumlah Barang Masuk
            </th>
            <th>
                Tanggal Masuk
            </th>
            <th>
                Dibuat Oleh
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var itemB in Model.allBar)
        {
                  
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => itemB.nama_barang)                    
                </td>
                <td>
                    @Html.DisplayFor(modelItem => itemB.nama_kategori)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => itemB.jumlah_barang)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => itemB.jum_barang_masuk)
                </td>
                <td>
                    @Convert.ToString(string.Format("{0:dd/MM/yyyy}", itemB.tanggal_masuk))
                </td>


                <td>
                    @foreach (var itemS in Model.allSup)
                    {
                        @Html.DisplayFor(a => itemS.nama_supplier)
                    }
                </td>

            </tr>
            //var c = 0; var cek = itemB.id_barang;
            //int cek = itemB.id_barang, i = 0, c = 0;
            //int[] cekAr = new int[50];
            //cekAr[i] = cek;
            //if (cekAr[i] == cekAr[i]) { c++; }                  

            //else if (cekAr[i] != cekAr[i-1]){<text> <tr style="border:groove;"></tr> </text>}
            //Write(c);
            //Write(i);
            
        }


    </tbody>
</table>

ManajemenBarang/Areas/Supplier/Views/Suppliersite/InsertData.cshtml
@{
    ViewBag.Title = "InsertData";
}

<h2>Insert Data Berhasil</h2>
<div>
    @Html.ActionLink("Kembali ke Awal", "Index")
</div>

ManajemenBarang/Areas/Supplier/Views/Suppliersite/InsertDataExist.cshtml
@{
    ViewBag.Title = "InsertDataExist";
}

<h2>Insert Data Existing Berhasil</h2>
<div>
    @Html.ActionLink("Kembali ke Awal", "Index")
</div>

ManajemenBarang/Areas/Supplier/Views/Suppliersite/Profil.cshtml
@model IEnumerable<ManajemenBarang.Models.GetProfil_Result>
@{
    ViewBag.Title = "Profil";
}
<style>
    .table th {
        text-align: center;
    }

    .table tr {
        text-align: center;
    }
</style>
<h2>Profil Supplier</h2>
<div>
    @Html.ActionLink("Kembali", "Index")
</div>
<table class="table table-bordered">
    @foreach (var a in Model)
    {

        <tr>
            <th>Nama</th>
            <td>@Html.DisplayFor(b => a.nama_supplier)</td>
        </tr>
        <tr>
            <th>Alamat</th>
            <td>@Html.DisplayFor(b => a.alamat_supplier)</td>
        </tr>
        <tr>
            <th>Telepon</th>
            <td>@Html.DisplayFor(b => a.telp_supplier)</td>
        </tr>
    }

</table>
<br />
<br />